name: CI for Scraper

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Install dependencies
      - name: Install dependencies
        run: |
          cd backend
          go mod tidy

      - name: Run golangci-lint
        working-directory: backend
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.52.2
          ./bin/golangci-lint run ./...

      # Run tests
      # - name: Run tests
      #   run: go test ./... -v
